### ISSUE TITLE
Introduce the "plugins group" concept 

### ISSUE THREAD

**Issue by Gsantomaggio** [kf5i/k3ai-core#12]
Per discussion with @alfsuse 

We need to introduce the `plugins group`. 
In this way, we can define a set of plugins to deploy together.
For example:
 - `minimal pipelines group` --> installs kubeflow pipelines and kfp sdk
- `jupyter pipelines` --> installs jupyter and kubeflow 

etc....

We will define some `plugins group` on the [plugin repo](https://github.com/kf5i/k3ai-plugins) by default.
The user must be able also to create its own local `plugins group` file.

As always I'd use a YAML file, something like:
```yaml
plugin-type: group
plugins:
    - pipelines
    - jupyter
```
etc...

**Comment by harsimranmaan** [comment]
What other plugin-types can be there?

**Comment by Gsantomaggio** [comment]
I was thinking to add:


* `plugin-type: standard` 
* `plugin-type: group`

so we leave the plugin spec opens for future plugin types
