### ISSUE TITLE
Add the cli command line parameters

### ISSUE THREAD

**Issue by Gsantomaggio** [kf5i/k3ai-core#15]
We have to add the standard commands to the `k3a-cli`tool.

Based on the @harsimranmaan's idea I'd start with two basic commands

```
k3ai-cli apply <<plugin_name>> or <<plug_group>>
k3ai-cli delete <<plugin_name>> or <<plug_group>>
```

for the local groups would be:
```
k3ai-cli apply --local (or -l)<<plugins_group>>
k3ai-cli delete --local (or -l)<<plugins_group>>
```

Plugins
```
k3ai-cli plugins list
k3ai-cli describe <<plugin_name>> or <<plugins_group>>
 
```
About the k3s installation, we are still thinking about that. For the moment k3ai is bound to k3s, but we are thinking also about kind. 

Let's delay a bit the installation decision

**Comment by harsimranmaan** [comment]
This can be closed in favor of #29 and #30
