### ISSUE TITLE
Possibility to use also kubectl

### ISSUE THREAD

**Issue by Gsantomaggio** [kf5i/k3ai-core#21]
Currently, we use `k3s kubectl` to execute all the commands
We'd need also to use `kubectl` directly for different reasons, like:

- no k3s cluster 
- remote cluster

**Comment by harsimranmaan** [comment]
I have been using kubectl directly for local testing as I don't have have a k3s env. Minor tweaks in deploy.go are needed to support it
 We need to decide the flag name for using kubectl instead of k3s
