### ISSUE TITLE
Wait during the installation

### ISSUE THREAD

**Issue by Gsantomaggio** [kf5i/k3ai-core#23]
Implement the `wait` functionality.  We  already have it on the [`k3ai`](https://github.com/kf5i/k3ai/blob/v0.1.4/install#L32-L50).

**Comment by harsimranmaan** [comment]
The shell wait works based on labels. To port the functionality here, it might be desired to have some label processing capabilities for the cli. For first party plugin script this is relatively easier to do as the plugin author can specify all labels in place. Eg. For v1 plugins. For v2 plugins where the install manifest is pulled from a third party repo, waiting on labels might be a bit tricky. Eg. The argo plugin. However, if we use the labels fields in the plugin spec, it might be easier to wait but a little of work would be needed to merge the labels to the k3s objects just before applying. Any other ideas are welcome.

**Comment by harsimranmaan** [comment]
@Gsantomaggio Do you think it would be ok to wait on the Labels specified in the labels array on the plugin spec?

**Comment by Gsantomaggio** [comment]
yes. 

Just one note:
I want to pass an ["event wait" ](https://github.com/kf5i/k3ai-core/blob/main/internal/k8s/kctl/deploy.go#L29)and not write the wait inside the [`apply`](https://github.com/kf5i/k3ai-core/blob/main/internal/k8s/kctl/deploy.go#L23).

This because in the future we want to write another "wait" function for the Web Application.


A bit off-topic:
The future idea is to  add events  (synchronous or asynchronous)  inside the deploy part to notify what is happening inside the library to external clients, for now, we have only the `cli` then web application an maybe we need to integrate it with https://github.com/kf5i/k3ai-cloud
