### ISSUE TITLE
Add ability to use local plugin

### ISSUE THREAD

**Issue by harsimranmaan** [kf5i/k3ai-core#30]
It is currently possible to use plugins from a remote github repo. The plugin repository can also be a local folder and might have other server type too in the future. `--plugin-repo` is already configurable to set different repo sources. It should be possible to infer local vs remote repo based on the repo uri. The uri scheme can be used a hint to decide which kind of repo to be used or an addition parameter like `--plugin-repo-type` can be introduced if needed. The `--plugin-repo-type` might not be needed until support for a new remote repo (eg: gitlab) is added.

**Comment by Gsantomaggio** [comment]
closed via https://github.com/kf5i/k3ai-core/pull/42
