### ISSUE TITLE
Add a doctor command to check prereqs

### ISSUE THREAD

**Issue by harsimranmaan** [kf5i/k3ai-core#8]
I got this idea from flutter. A doctor command is extremely helpful in scenarios when the users are troubleshooting issues. Since there are a few dependencies(k3s kubectl) that are expected to be installed before k3ai can work, a doctor command can be used to list errors if the deps are missing. This can evolve into a more detailed diagnostic with auto-remediation capabilities in the future. The output would also be helpful when someone wants to file defects as more diagnostic information can be built into this command as needed.

**Comment by saiyam1814** [comment]
Didn't quite get the need here for a docker command which leads to a prereq of having docker itself. 
When you have k3s installed, k3s kubectl will automatically be there.

**Comment by alefesta** [comment]
Closing due inactivity
