### ISSUE TITLE
On OpenSuse + K3S Setup Jupyter-Minimal-Traefik fails to install packages via pip due to internet connection timeout

### ISSUE THREAD

**Issue by ranjanprj** [kf5i/k3ai-core#88]
I recently installed K3ai on following setup

1. OpenSuse 15.x
2. K3s - 21.x
3. VirtualBox on Windows - Bridged Network

Issue
------
After I install the jupyter-minimal-traefik on K3S, everything works except when I try to install
pip packages using terminal, then  it is not able to connect to internet.

Steps to Reproduce:
----------------------

1. Install OpenSuse 15.x on VirtualBox with Bridged Adapter Network
2. Install K3s 21.x
3. Install k3ai for k3s
4. Install k3ai jupyter-minimal-traefik package
5. Open Jupyter notebook and launch terminal window in web browser
6. Issue command `pip install numpy`
7. You will get internet connection timeout error

This is error message PIP install and WGET command
Error Message
```
base) jovyan@jupyter-minimal-6565df8f74-6w2cf:~$ pip install numpy
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9dfc88b520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/numpy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 
ERROR: No matching distribution found for numpy


(base) jovyan@jupyter-minimal-6565df8f74-6w2cf:~$ wget https://linux.org
--2021-08-30 11:49:16--  https://linux.org/
Resolving linux.org (linux.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘linux.org’
(base) jovyan@jupyter-minimal-6565df8f74-6w2cf:~$ ^C
(base) jovyan@jupyter-minimal-6565df8f74-6w2cf:~$

```

![image](https://user-images.githubusercontent.com/774370/131334194-5cae844e-0a33-4fdc-a6c1-4a2764103723.png)

Troubleshooting
-----------------
1. I created a busybox pod in the same cluster in K3s on OpenSuse and it is able to connect to internet, so connectivity with other pods is there.
2. Checked Proxy settings, but there is none in OpenSuse, also I'm able to browse internet fine from within OpenSuse Firefox browser.
2. I installed k3ai and K3s on Ubuntu Server 20.x and everything works fine in this setup including installing any packages from pip with same Bridged Adapter Network.

Another busybox pod in the same cluster is able to connect to internet 

![image](https://user-images.githubusercontent.com/774370/131334488-521c4170-0403-4004-92d1-3a3bb256301a.png)

```
rebataur@localhost:~> sudo kubectl get pods
NAME         READY   STATUS    RESTARTS   AGE
shell-demo   1/1     Running   1          39h
rebataur@localhost:~> sudo kubectl exec --stdin --tty shell-demo -- /bin/bash
root@localhost:/# curl -Is http://www.google.com | head -n 1
HTTP/1.1 200 OK

```

So the issue is that why Jupyter-Minimal is not able to connect to internet and install pip packages.

**Comment by alefesta** [comment]
hi @ranjanprj the jupyter-minimal actually should do 2 things:
1) deploy a standard  jupyter server image from *jupyter/minimal-notebook* official image running in it
2) if used in combination with traefik be exposed to the outside world
Said that has no other configurations so it should be able to reach out the internet as any other pod.

I've tested it on my local setup and seems to work fine
![pip](https://user-images.githubusercontent.com/80312181/131470850-df41e162-3884-4bc6-bc5e-0e604ff6b959.JPG)

just to confirm did you installed with
`k3ai apply -g jupyter-minimal-traefik` ?

**Comment by alefesta** [comment]
close due inactivty
