### ISSUE TITLE
[Changes] - Rename K3ai Organization and refresh list of official contributors

### ISSUE THREAD

**Issue by alefesta** [kf5i/k3ai-core#90]
We used to have a good list of contributors but in the past 6 months, those were quite silent. This proposal is to introduce a governance model that stands like this:

## Governance Model

1.  If a contributor does not actively participate in the project for more than 6 months will be downgraded to standard member
     a. all the contributions will still be listed but it will be removed from the owners/reviewers list
2. If a contributor wants to stay active has to keep participating in the project.

## Organizational rename
The idea is to make easier for ppl to find K3ai project to rename the Org from **Kf5i** to **k3ai-project**

**Please feel free to comment out. If after 2 weeks from opening this issue will be no outstanding objection the changes will be processed.**

**Comment by alefesta** [comment]
Project name re-organization is going will become active when v3 will be released

**Comment by Gsantomaggio** [comment]
Agree!

**Comment by dottorblaster** [comment]
No problem for me so far :+1:

**Comment by alfsuse** [comment]
Moved website to https://k3ai.in  and org to https://github.com/k3ai
